server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: root
jpa:
  generate-ddl: true
  show-sql: true
  hibernate:
#    dialect: org.hibernate.dialect.PostgreSQL9Dialect
    ddl-auto: update


